### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by dunnkers** [godatadriven/mlops-workshop#2]
- [x] Clean up Venn diagram slide (colors and text should match)
- [x] Validate answers are not inside notebooks (or at least _hidden_) @ykerus @dunnkers 
- [x] Make GitHub repo public
- [x] Update slide PDF in GitHub repo
- [x] Change reference of https://xebia.ai/mlops link
- [x] @dunnkers Deployment klaar zetten met **ACI**
